apiVersion: v1
kind: Service
metadata:
  labels:
    run: tensorflow-server
  name: tensorflow-server
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    run: tensorflow-server
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorflow-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tensorflow-server
    spec:
      containers:
      - name: tensorflow-server
        command: ["/bin/sh", "-c"]
        args: ["python /app/src/app.py"]
        image: sozercan/tf-server
        env:
        - name: STORAGE_ACCOUNT_NAME
          value:
        - name: STORAGE_ACCOUNT_KEY
          value:
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 2
