apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: tensorflow-trainer
  name: tensorflow-trainer
spec:
  template:
    metadata:
      name: tensorflow-trainer
    spec:
      containers:
      - args:
        command: ["/bin/sh", "-c"]
        args: [python /app/src/app.py --train"]
        image: sozercan/tf-server
        name: tensorflow-trainer
        env:
        - name: STORAGE_ACCOUNT_NAME
          value:
        - name: STORAGE_ACCOUNT_KEY
          value:
      restartPolicy: Never