version: '2'
services:
  cpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: sozercan/tf-server
  gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: sozercan/tf-server-gpu