FROM gcr.io/tensorflow/tensorflow:latest-gpu

RUN apt-get update
RUN apt-get install -qq build-essential libssl-dev libffi-dev python-dev curl
RUN pip install Flask azure-storage
RUN apt-get install -qq python-qt4
RUN pip uninstall -y numpy
RUN pip install --no-binary=:all: numpy

RUN echo "LD_LIBRARY_PATH='/usr/lib/x86_64-linux-gnu_custom:$LD_LIBRARY_PATH'" >> ~/.profile
RUN echo "LD_LIBRARY_PATH='/usr/lib/x86_64-linux-gnu_custom:$LD_LIBRARY_PATH'" >> ~/.bashrc

COPY ./ /app

EXPOSE 80